### ISSUE TITLE
:top-interval=10；属性失效

### ISSUE THREAD

**Issue by SK-ERIC** [geng452654716/vue-waterfall#3]
cdn 引入vue-waterfall-adaptive.js ，这个属性 :top-interval=10，只在第一次加载第一屏数据时有效，load更多后，就失效了
![image](https://user-images.githubusercontent.com/52649359/77995527-885ae600-735e-11ea-82bc-5ef176abced4.png)

**Comment by geng452654716** [comment]
多谢反馈，已修复
